# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 22:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskitem',
            options={'permissions': (('add_reminder', 'Add reminder'), ('delete_reminder', 'Delete reminder'), ('delete_task', 'Delete task'), ('edit_task', 'Edit task'))},
        ),
    ]
